export const INGREDIENTS = [
  "chickpeas",
  "lentils",
  "black beans",
  "tofu",
  "tempeh",
  "mushrooms",
  "spinach",
  "kale",
  "tomato",
  "onion",
  "garlic",
  "chili",
  "ginger",
  "potato",
  "sweet potato",
  "eggplant",
  "zucchini",
  "broccoli",
  "rice",
  "pasta",
  "coconut milk",
  "peanut",
  "lemon",
  "avocado",
  "corn",
  "oats",
  "banana",
  "berries",
  "eggs",
  "yogurt",
];

export const RECIPES = [
  {
    id: "coconut-chickpea",
    diet: "vegan",
    title: "Chickpea coconut curry",
    time: "30 min",
    servings: "3",
    ingredients: ["chickpeas", "coconut milk", "tomato", "garlic", "ginger", "chili", "onion", "rice"],
    pantry: ["1 can chickpeas", "1 can coconut milk", "2 tomatoes or 1 cup crushed", "3 garlic cloves", "1 onion", "thumb of ginger", "chili to taste", "rice"],
    steps: [
      "Rinse rice and start it simmering.",
      "Soften onion, garlic, ginger, and chili in a little oil.",
      "Add tomato and cook until jammy.",
      "Stir in chickpeas and coconut milk. Salt. Simmer 12 minutes.",
      "Serve over rice. Squeeze lemon if you have it.",
    ],
    why: "Chickpeas and rice replace a meat curry with a fraction of the land and methane.",
  },
  {
    id: "lentil-ragu",
    diet: "vegan",
    title: "Lentil ragu",
    time: "35 min",
    servings: "4",
    ingredients: ["lentils", "tomato", "garlic", "onion", "pasta"],
    pantry: ["1 cup dry brown lentils", "1 onion", "3 garlic cloves", "2 cups tomato", "pasta", "olive oil", "salt"],
    steps: [
      "Boil lentils in salted water until just tender. Drain.",
      "Cook pasta.",
      "Soften onion and garlic. Add tomato. Simmer 10 minutes.",
      "Fold in lentils. Loosen with pasta water.",
      "Toss with pasta. Black pepper on top.",
    ],
    why: "Lentils give the weight of a meat sauce without the herd.",
  },
  {
    id: "tofu-stir",
    diet: "vegan",
    title: "Garlic ginger tofu",
    time: "20 min",
    servings: "2",
    ingredients: ["tofu", "broccoli", "garlic", "ginger", "rice"],
    pantry: ["1 block firm tofu", "1 head broccoli", "3 garlic cloves", "ginger", "soy sauce", "rice"],
    steps: [
      "Press tofu. Cube it. Brown in a hot pan.",
      "Steam or sear broccoli until bright.",
      "Add garlic and ginger for 30 seconds.",
      "Splash soy sauce. Toss. Eat with rice.",
    ],
    why: "Tofu is one of the lowest-carbon proteins you can cook in a weeknight pan.",
  },
  {
    id: "bean-tacos",
    diet: "vegan",
    title: "Black bean tacos",
    time: "20 min",
    servings: "3",
    ingredients: ["black beans", "tomato", "avocado", "chili", "corn", "onion"],
    pantry: ["1 can black beans", "1 tomato", "1 avocado", "chili", "corn tortillas or corn", "onion"],
    steps: [
      "Warm beans with chili, onion, and a pinch of salt.",
      "Chop tomato. Smash avocado with lemon if you have it.",
      "Fill tortillas. Add corn.",
      "Eat with your hands.",
    ],
    why: "Beans plus tortillas beat ground beef on climate, water, and cost.",
  },
  {
    id: "mushroom-rice",
    diet: "vegan",
    title: "Mushroom garlic rice",
    time: "28 min",
    servings: "3",
    ingredients: ["mushrooms", "garlic", "onion", "rice"],
    pantry: ["400g mushrooms", "1 onion", "4 garlic cloves", "1 cup rice", "oil", "salt"],
    steps: [
      "Cook rice.",
      "Sear mushrooms in a wide pan until they brown and shrink.",
      "Add onion then garlic. Do not rush.",
      "Fold through rice. Salt. Eat hot.",
    ],
    why: "Mushrooms give the roast-meat note. No animal required.",
  },
  {
    id: "peanut-bowl",
    diet: "vegan",
    title: "Peanut tofu bowl",
    time: "25 min",
    servings: "2",
    ingredients: ["tofu", "peanut", "rice", "spinach", "garlic"],
    pantry: ["tofu", "2 tbsp peanut butter", "rice", "a pile of spinach", "garlic", "soy sauce"],
    steps: [
      "Cook rice. Brown tofu.",
      "Whisk peanut butter with soy, water, and grated garlic.",
      "Wilt spinach in the tofu pan.",
      "Bowl it. Pour the sauce.",
    ],
    why: "Peanuts and tofu cover protein without the feedlot.",
  },
  {
    id: "shakshuka",
    diet: "vegetarian",
    title: "Tomato chili eggs",
    time: "25 min",
    servings: "2",
    ingredients: ["eggs", "tomato", "chili", "garlic", "onion"],
    pantry: ["4 eggs", "4 tomatoes or 1 can", "1 onion", "3 garlic cloves", "chili", "oil"],
    steps: [
      "Soften onion, garlic, and chili.",
      "Add tomato. Cook until thick.",
      "Make wells. Crack in eggs. Cover until the whites set.",
      "Bread or rice on the side.",
    ],
    why: "Eggs still cost more than plants, but far less than beef. A first step off meat.",
  },
  {
    id: "spinach-tofu",
    diet: "vegan",
    title: "Spinach tomato tofu",
    time: "30 min",
    servings: "3",
    ingredients: ["spinach", "tofu", "tomato", "garlic", "onion", "ginger"],
    pantry: ["1 block tofu", "a lot of spinach", "tomato", "onion", "garlic", "ginger"],
    steps: [
      "Blend or mash tomato with garlic and ginger.",
      "Brown onion. Add the tomato mix.",
      "Cube tofu into the sauce. Simmer 8 minutes.",
      "Fold spinach until it collapses.",
    ],
    why: "A palak-style pot without dairy, and without a cow.",
  },
  {
    id: "sweet-chili",
    diet: "vegan",
    title: "Sweet potato chili",
    time: "40 min",
    servings: "4",
    ingredients: ["sweet potato", "black beans", "tomato", "chili", "onion", "garlic"],
    pantry: ["2 sweet potatoes", "1 can black beans", "tomato", "onion", "garlic", "chili"],
    steps: [
      "Cube sweet potato. Soften onion and garlic.",
      "Add chili, tomato, sweet potato, and a cup of water.",
      "Simmer until the potato gives.",
      "Stir in beans. Salt. Rest 5 minutes.",
    ],
    why: "One pot. High protein. Almost no climate cost next to beef chili.",
  },
  {
    id: "eggplant-bake",
    diet: "vegan",
    title: "Eggplant tomato bake",
    time: "45 min",
    servings: "3",
    ingredients: ["eggplant", "tomato", "garlic", "onion"],
    pantry: ["2 eggplants", "tomato sauce", "garlic", "onion", "oil", "salt"],
    steps: [
      "Slice eggplant. Salt. Roast at 220°C until soft and browned.",
      "Cook onion, garlic, and tomato into a sauce.",
      "Layer eggplant and sauce. Bake 15 minutes more.",
    ],
    why: "The roast and the sauce do the comfort work that cheese and meat usually steal.",
  },
  {
    id: "lemon-zucchini",
    diet: "vegan",
    title: "Lemon zucchini pasta",
    time: "18 min",
    servings: "2",
    ingredients: ["pasta", "zucchini", "lemon", "garlic"],
    pantry: ["pasta", "2 zucchini", "1 lemon", "3 garlic cloves", "olive oil"],
    steps: [
      "Boil pasta.",
      "Ribbon or slice zucchini. Sauté with garlic.",
      "Toss with pasta, lemon zest, lemon juice, and oil.",
      "Pasta water if it needs silk.",
    ],
    why: "Dinner in the time it takes to boil water. No animal in the pot.",
  },
  {
    id: "oat-bowl",
    diet: "vegan",
    title: "Berry banana oats",
    time: "8 min",
    servings: "1",
    ingredients: ["oats", "banana", "berries"],
    pantry: ["1/2 cup oats", "1 banana", "a handful of berries", "water or plant milk"],
    steps: [
      "Simmer oats in water or plant milk.",
      "Slice banana in. Berries on top.",
      "That is breakfast.",
    ],
    why: "Dairy-free oats skip the cow and still fill you.",
  },
  {
    id: "yogurt-bowl",
    diet: "vegetarian",
    title: "Yogurt berry bowl",
    time: "5 min",
    servings: "1",
    ingredients: ["yogurt", "berries", "banana", "oats"],
    pantry: ["yogurt", "berries", "banana", "a spoon of oats"],
    steps: [
      "Spoon yogurt into a bowl.",
      "Add banana, berries, and oats.",
      "Eat before you talk yourself into something worse.",
    ],
    why: "Dairy is not free, but this bowl still beats a bacon breakfast by a mile.",
  },
  {
    id: "tempeh-kale",
    diet: "vegan",
    title: "Tempeh kale skillet",
    time: "22 min",
    servings: "2",
    ingredients: ["tempeh", "kale", "garlic", "lemon"],
    pantry: ["1 pack tempeh", "kale", "garlic", "lemon", "soy sauce"],
    steps: [
      "Slice tempeh. Brown it hard.",
      "Add garlic. Pile in kale.",
      "Soy sauce. Lemon. Serve.",
    ],
    why: "Tempeh is fermented soy. Dense protein. Tiny footprint.",
  },
  {
    id: "corn-avocado",
    diet: "vegan",
    title: "Corn avocado plate",
    time: "12 min",
    servings: "2",
    ingredients: ["corn", "avocado", "lemon", "chili", "tomato"],
    pantry: ["2 cobs or 2 cups corn", "1 avocado", "lemon", "chili", "tomato"],
    steps: [
      "Char or boil the corn.",
      "Chop tomato. Smash avocado with lemon and chili.",
      "Pile together. Salt.",
    ],
    why: "A side that can be lunch. No meat, no performance.",
  },
  {
    id: "potato-lentil",
    diet: "vegan",
    title: "Roast potato lentils",
    time: "40 min",
    servings: "3",
    ingredients: ["potato", "lentils", "garlic", "onion", "lemon"],
    pantry: ["4 potatoes", "1 cup lentils", "onion", "garlic", "lemon", "oil"],
    steps: [
      "Roast cubed potatoes with oil and salt until crisp.",
      "Boil lentils with onion and garlic.",
      "Toss together. Lemon over the top.",
    ],
    why: "The roast you want on a cold night, built from the cheapest plants.",
  },
];
